spring:
  application:
    name: Authentication
    timezone: Asia/Kolkata
  datasource:
    url: jdbc:mysql://localhost:3306/taleTrade
    username: root
    password: anandhu@12
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081